### ISSUE TITLE
Tailwind given instead of Bootstrap

### ISSUE THREAD

**Issue by sreeram-venkitesh** [dalezak/rails-blueprint#1]
Hey I was going through the readme and noticed that in the [Create Project](https://github.com/dalezak/rails-blueprint#create-project) section, `tailwindcss` has been mentioned as the css option under the `Postgres + Bootstrap + Rollup` section

<img width="891" alt="Screen Shot 2022-01-07 at 11 59 54 AM" src="https://user-images.githubusercontent.com/40194401/148503940-86e901c0-b834-4a56-a7bf-975fe01bae07.png">

So this should either have `bootstrap` as css or it should be `Postgres + Tailwind + Rollup` right?

**Comment by dalezak** [comment]
Thanks for pointing that out @sreeram-venkitesh, I'll add it 👍
